### ISSUE TITLE
Failing API submissions

### ISSUE THREAD

**Issue by muellerberndt** [aquiladev/mythxl#3]
Looking at the [website](https://mythxl-ui.azurewebsites.net) it appears that MythXL somehow submits invalid bytecodes as analyses are all failing.

My guess is that MythXL is submitting runtime bytecode in the `bytecode` field. For the analysis to succeed, MythX requires the *creation* bytecode, i.e.:

```
{ contractName: 'SomeName',
  bytecode:
   '[creation-bytecode]',
  sourceMap:
   '[sourceMap',
  deployedBytecode:
   '[runtime-bytecode'],
  deployedSourceMap:
   '[runtime-sourcemap]',
(...)
```

Please make sure that the submitted format is correct!

**Comment by aquiladev** [comment]
You are right, I submit code from chain, which does not have creation part

I'll update the logic
